server:
  port: 8088
  servlet:
    context-path: /profits
spring:
  application:
    name: petty-profits
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 3
        max-wait: 1s
  shardingsphere:
    datasource:
      names: db
      db:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/profits_db?characterEncoding=utf-8&connectTimeout=2000&socketTimeout=2000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
    props:
      sql:
        show: false
    sharding:
      tables:
        t_stock_kline:
          actual-data-nodes: db.t_stock_kline_$->{1990..2022}
          table-strategy:
            standard:
              sharding-column: deal_time
              precise-algorithm-class-name: io.github.tf2jaguar.pettyprofits.sharding.KlineShardingAlgorithm


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,health
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
