server:
  port: 8088
  servlet:
    context-path: /profits
spring:
  application:
    name: petty-profits
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?characterEncoding=utf-8&connectTimeout=2000&socketTimeout=2000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 3
        max-wait: 1s
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,health
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
